---
- hosts: wordpress
  handlers:
     - name: restart apache
       service:
         name: apache2
         state: restarted
  become: yes

  tasks:
    - name: 'Instalar pacotes de dependencia do OS'
      apt:
        name:
        - php7.0
        - apache2
        - libapache2-mod-php7.0
        - php-gd
       # - libssh2-php
       # - php-mcrypt
        - mysql-server
        - python-mysqldb
        - php-mysql
        - python-pymysql
        state: latest
      become: yes

    - name: 'Cria banco de dados MySQL'
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: wordpress_db
        login_user: root
        state: present
    #  become: yes
    
    - name: 'Cria user MySQL'
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present

    - name: 'Download Wordpress Latest'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
        mode: 0777
    
    - name: 'Descompacta Wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www/
        remote_src: yes
      become: yes

    - name: 'Copia arquivo de configuração'
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Ajusta arquivo de configuração'
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
        backup: yes
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress_user'}
        - { regex: 'password_here', value: '12345'}
      become: yes

    - name: 'Configura Apache para servir Wordpress'
      copy:
        src: 'files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - restart apache